/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutDashboardImport } from './routes/_layout-dashboard'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const LayoutDashboardSearchIndexLazyImport = createFileRoute(
  '/_layout-dashboard/search/',
)()
const LayoutDashboardProfileIndexLazyImport = createFileRoute(
  '/_layout-dashboard/profile/',
)()
const LayoutDashboardHomeIndexLazyImport = createFileRoute(
  '/_layout-dashboard/home/',
)()
const LayoutDashboardFollowingIndexLazyImport = createFileRoute(
  '/_layout-dashboard/following/',
)()
const LayoutDashboardExploreIndexLazyImport = createFileRoute(
  '/_layout-dashboard/explore/',
)()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const LayoutDashboardRoute = LayoutDashboardImport.update({
  id: '/_layout-dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LayoutDashboardSearchIndexLazyRoute =
  LayoutDashboardSearchIndexLazyImport.update({
    path: '/search/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_layout-dashboard/search/index.lazy').then((d) => d.Route),
  )

const LayoutDashboardProfileIndexLazyRoute =
  LayoutDashboardProfileIndexLazyImport.update({
    path: '/profile/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_layout-dashboard/profile/index.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutDashboardHomeIndexLazyRoute =
  LayoutDashboardHomeIndexLazyImport.update({
    path: '/home/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_layout-dashboard/home/index.lazy').then((d) => d.Route),
  )

const LayoutDashboardFollowingIndexLazyRoute =
  LayoutDashboardFollowingIndexLazyImport.update({
    path: '/following/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_layout-dashboard/following/index.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutDashboardExploreIndexLazyRoute =
  LayoutDashboardExploreIndexLazyImport.update({
    path: '/explore/',
    getParentRoute: () => LayoutDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_layout-dashboard/explore/index.lazy').then(
      (d) => d.Route,
    ),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layout-dashboard': {
      preLoaderRoute: typeof LayoutDashboardImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/_layout-dashboard/explore/': {
      preLoaderRoute: typeof LayoutDashboardExploreIndexLazyImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout-dashboard/following/': {
      preLoaderRoute: typeof LayoutDashboardFollowingIndexLazyImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout-dashboard/home/': {
      preLoaderRoute: typeof LayoutDashboardHomeIndexLazyImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout-dashboard/profile/': {
      preLoaderRoute: typeof LayoutDashboardProfileIndexLazyImport
      parentRoute: typeof LayoutDashboardImport
    }
    '/_layout-dashboard/search/': {
      preLoaderRoute: typeof LayoutDashboardSearchIndexLazyImport
      parentRoute: typeof LayoutDashboardImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  LayoutDashboardRoute.addChildren([
    LayoutDashboardExploreIndexLazyRoute,
    LayoutDashboardFollowingIndexLazyRoute,
    LayoutDashboardHomeIndexLazyRoute,
    LayoutDashboardProfileIndexLazyRoute,
    LayoutDashboardSearchIndexLazyRoute,
  ]),
  AboutLazyRoute,
])

/* prettier-ignore-end */
